import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { FlipWords } from "../components/flip-words";
import { motion } from "framer-motion";
import { LampContainer } from "../components/lamp";
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import { useAccount } from 'wagmi';

const Home: NextPage = () => {
  const router = useRouter();
  const { address, isConnected } = useAccount();

  useEffect(() => {
    if (isConnected) {
      router.push('/reception'); // Corrected path to reception
    }
  }, [isConnected, router]);

  const words = ["Mafia", "Starknet", "RainbowKit", "Web3", "Ethereum"];

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">Starknet</a> <a href="">Mafia</a>
        </h1>

        <p className={styles.description}>
          Get into a game of Mafia
        </p>

        <div className="relative">
          <div className={styles.emojis}>
            <span className={styles.emoji} style={{ top: '10%', left: '20%' }}>🕵️‍♂️</span>
            <span className={styles.emoji} style={{ top: '50%', left: '50%' }}>💰</span>
            <span className={styles.emoji} style={{ top: '30%', left: '70%' }}>🔫</span>
            <span className={styles.emoji} style={{ top: '80%', left: '40%' }}>🚬</span>
            <span className={styles.emoji} style={{ top: '20%', left: '80%' }}>🕵️‍♀️</span>
          </div>
        </div>

        <ConnectButton />
      </main>
    </div>
  );
};

export default Home;
